import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="p-8">
      { children }
    </div>
  );
}
