import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Protected Page",
  description: "Generated by create next app",
};

export default function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-auto">
      <div className="hidden lg:flex flex-col w-72 h-dvh shadow-2xl bg-white sticky top-0">
        <Sidebar />
      </div>
      <div className="flex flex-col flex-1 overflow-y-auto p-3">
        <Navbar />
        {children}
      </div>
    </div>
  );
}
