import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Protected Page",
  description: "Generated by create next app",
};

export default function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-auto">
      <div className="hidden lg:flex flex-col w-64 h-dvh shadow-sidebar bg-white sticky top-0">
        <Sidebar />
      </div>
      <div className="flex flex-col flex-1 overflow-y-auto p-3">
        <div className="flex items-center justify-between h-16 shadow-navbar rounded-lg bg-white">
          <Navbar />
        </div>
        {children}
      </div>
    </div>
  );
}
